### ISSUE TITLE
If hot fn returns malformed response server should be more explicit on what went wrong

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#355]
If function returns malformed HTTP response server returns to a user HTTP 500 Internal Server Error, but in server logs we see more verbose error:
```
ERRO[1283] internal server error                         action="server.handleRunnerRequest)-fm" app=testapp error="malformed HTTP status code \"established\"" id=01BTNMVEHJ08S0A00000000000 route=/hot-json stack="goroutine 1485 [running]:\nruntime/debug.Stack(0x0, 0x0, 0x0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xbe\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x56a8500, 0xc42056d3b0, 0x5e71918, 0xc4203b38c0, 0x5697ac0, 0xc42043c060)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/error_response.go:37 +0x4bf\ngithub.com/fnproject/fn/api/server.handleErrorResponse(0xc4203b38c0, 0x5697ac0, 0xc42043c060)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/error_response.go:24 +0xae\ngithub.com/fnproject/fn/api/server.(*Server).serve(0xc420392090, 0xc4203b38c0, 0xc4204082a8, 0x7, 0xc4204082af, 0x9)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/runner.go:109 +0x677\ngithub.com/fnproject/fn/api/server.(*Server).handleRequest(0xc420392090, 0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/runner.go:44 +0x248\ngithub.com/fnproject/fn/api/server.(*Server).handleRunnerRequest(0xc420392090, 0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/server.go:213 +0x35\ngithub.com/fnproject/fn/api/server.(*Server).(github.com/fnproject/fn/api/server.handleRunnerRequest)-fm(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/server.go:298 +0x34\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:110 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/server.go:192 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:110 +0x43\ngithub.com/fnproject/fn/api/server.traceWrap(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/server.go:114 +0x2e9\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:110 +0x43\ngithub.com/fnproject/fn/api/server.loggerWrap(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/server.go:209 +0x17c\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:110 +0x43\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc42009a900, 0xc4203b38c0)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:344 +0x5c5\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc42009a900, 0x56a73c0, 0xc42062ea80, 0xc420138f00)\n\t/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:311 +0x16b\nnet/http.serverHandler.ServeHTTP(0xc420080c30, 0x56a73c0, 0xc42062ea80, 0xc420138f00)\n\t/usr/local/go/src/net/http/server.go:2619 +0x1e2\nnet/http.(*conn).serve(0xc420132820, 0x56a8440, 0xc42056e440)\n\t/usr/local/go/src/net/http/server.go:1801 +0x125d\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2720 +0x734\n"
```

We might let users know if their function fails to be good one for http format.

**Comment by denismakogon** [comment]
The type of error is: `malformed HTTP status code`, it comes from [here](https://github.com/golang/go/blob/d3c1df712658398f29bc8bebd6767e7b3cac2d12/src/net/http/response.go#L174), can happen if FDK writes bad output which is malformed for the protocol.

**Comment by denismakogon** [comment]
There's one way to reproduce this. Create a function without involving FDK, it should handle only default protocol (simple echo function), make that function hot with HTTP format, call it.
