### ISSUE TITLE
Fn  calls  failing with "inconsistent label cardinality"  prometheus errors 

### ISSUE THREAD

**Issue by zootalures** [fnproject/fn#464]
As of about 0.3.163 or 0.3.164  APi calls are panicing with errors: 

```
time="2017-10-26T13:07:12Z" level=info msg="starting call" action="server.handleRunnerRequest)-fm" app=travel container_id=01BXCCPBR867WG400000000000 id=01BXCCPBN367WG200000000000 route=/trip
panic: inconsistent label cardinality

goroutine 158 [running]:
github.com/fnproject/fn/vendor/github.com/prometheus/client_golang/prometheus.(*MetricVec).With(0xc420650000, 0xc4201d3020, 0xc42019afe0, 0xc420011980)
	/go/src/github.com/fnproject/fn/vendor/github.com/prometheus/client_golang/prometheus/vec.go:146 +0x76
github.com/fnproject/fn/vendor/github.com/prometheus/client_golang/prometheus.(*HistogramVec).With(0xc4204fa598, 0xc4201d3020, 0x14, 0xc42019afe0)
	/go/src/github.com/fnproject/fn/vendor/github.com/prometheus/client_golang/prometheus/histogram.go:344 +0x38
github.com/fnproject/fn/api/server.PrometheusCollector.Collect(0xc4204cb890, 0xc4203c3800, 0x3b9c6a843, 0x1a5c7a0)
	/go/src/github.com/fnproject/fn/api/server/prom_zip_collector.go:51 +0x94
github.com/fnproject/fn/api/server.(*PrometheusCollector).Collect(0xc420542198, 0xc4203c3800, 0x3b9c6a843, 0x1a5c7a0)
	<autogenerated>:1 +0x46
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*Recorder).RecordSpan(0xc42019c1e0, 0x23b3d946e6f61be3, 0x3e40767a31786250, 0x1ac25441f6f41e58, 0x1, 0xc4201491a0, 0xc420335190, 0x0, 0x1, 0x11a652d, ...)
	/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/zipkin-recorder.go:186 +0x6ee
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*spanImpl).FinishWithOptions(0xc4203ed6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/span.go:241 +0xc8d
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*spanImpl).Finish(0xc4203ed6c0)
	/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/span.go:175 +0x56
github.com/fnproject/fn/api/server.FnSpan.Finish(0x1a1f1c0, 0xc4203ed6c0)
	/go/src/github.com/fnproject/fn/api/server/fntracer.go:40 +0x49
github.com/fnproject/fn/api/server.(*FnSpan).Finish(0xc42049fa90)
	<autogenerated>:1 +0x45
github.com/fnproject/fn/api/agent/drivers/docker.(*dockerWrap).InspectImage(0xc4203c6ee0, 0x1a1a300, 0xc4203351c0, 0xc42017c210, 0x22, 0xc4200f5600, 0x0, 0x0)
	/go/src/github.com/fnproject/fn/api/agent/drivers/docker/docker_client.go:257 +0x205
github.com/fnproject/fn/api/agent/drivers/docker.(*DockerDriver).ensureImage(0xc4200545c0, 0x1a1a3c0, 0xc420149140, 0x1a1ec00, 0xc4200bca10, 0xc42017c180, 0x4)
	/go/src/github.com/fnproject/fn/api/agent/drivers/docker/docker.go:211 +0x29a
github.com/fnproject/fn/api/agent/drivers/docker.(*DockerDriver).Prepare(0xc4200545c0, 0x1a1a3c0, 0xc420149140, 0x1a1ec00, 0xc4200bca10, 0x60020520e58, 0x18, 0x20, 0xc4204f3d80)
	/go/src/github.com/fnproject/fn/api/agent/drivers/docker/docker.go:131 +0xc85
github.com/fnproject/fn/api/agent.(*agent).prepCold(0xc42024c0c0, 0x1a1a300, 0xc4203350c0, 0xc420324b40, 0xc42007ad70, 0x1a08100, 0xc42045a160, 0xc420324c60, 0xdb8f3c)
	/go/src/github.com/fnproject/fn/api/agent/agent.go:558 +0x223
github.com/fnproject/fn/api/agent.(*agent).launch.func1(0xc42024c0c0, 0x1a1a300, 0xc4203350c0, 0xc420324b40, 0xc42007ad70, 0x1a08100, 0xc42045a160, 0xc420244d20)
	/go/src/github.com/fnproject/fn/api/agent/agent.go:527 +0x77
created by github.com/fnproject/fn/api/agent.(*agent).launch
	/go/src/github.com/fnproject/fn/api/agent/agent.go:526 +0x159
```

**Comment by nigeldeakin** [comment]
See analysis and proposed "fix" in https://github.com/fnproject/fn/pull/465
