### ISSUE TITLE
Runner panics when starting runner node with wrong/unreachable FN_RUNNER_API_URL

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#593]
When FN_RUNNER_API_URL is not reachable runner crashes with panic
```
FN_LOG_LEVEL=ERROR FN_NODE_TYPE=runner FN_PORT=8082 FN_RUNNER_API_URL=http://localhost:8081 ./fnserver
ERRO[0000] error from API server, retrying               error="Get http://localhost:8081/v1/runner/async: dial tcp [::1]:8081: getsockopt: connection refused"

        ______
       / ____/___
      / /_  / __ \
     / __/ / / / /
    /_/   /_/ /_/
        v0.3.235

panic: interface conversion: opentracing.SpanContext is opentracing.noopSpanContext, not zipkintracer.SpanContext

goroutine 54 [running]:
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*tracerImpl).startSpanWithOptions(0xc4200de100, 0x4f93691, 0x15, 0xc4203d3900, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/tracer.go:309 +0xb36
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*tracerImpl).StartSpan(0xc4200de100, 0x4f93691, 0x15, 0xc4203a2080, 0x1, 0x1, 0xc420496000, 0xc420509b90)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/tracer.go:268 +0xdd
github.com/fnproject/fn/api/server.FnTracer.StartSpan(0x55c0900, 0xc4200de100, 0x4f93691, 0x15, 0xc4203a2080, 0x1, 0x1, 0xc4203a2080, 0x4e74900)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/server/fntracer.go:23 +0x73
github.com/fnproject/fn/api/server.(*FnTracer).StartSpan(0xc4204f3340, 0x4f93691, 0x15, 0xc4203a2080, 0x1, 0x1, 0x0, 0x1)
	<autogenerated>:1 +0x82
github.com/fnproject/fn/vendor/github.com/opentracing/opentracing-go.startSpanFromContextWithTracer(0x55c2980, 0xc420192cf0, 0x55bad00, 0xc4204f3340, 0x4f93691, 0x15, 0x0, 0x0, 0x0, 0x10, ...)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/opentracing/opentracing-go/gocontext.go:52 +0x12a
github.com/fnproject/fn/vendor/github.com/opentracing/opentracing-go.StartSpanFromContext(0x55c2980, 0xc420192cf0, 0x4f93691, 0x15, 0x0, 0x0, 0x0, 0xc42007a840, 0x20002, 0xc420509d9c, ...)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/vendor/github.com/opentracing/opentracing-go/gocontext.go:44 +0x95
github.com/fnproject/fn/api/agent/hybrid.(*client).once(0xc4203f2c20, 0x55c2980, 0xc420192cf0, 0x0, 0x0, 0x4d7bbe0, 0xc4203f2e20, 0x4f7c908, 0x3, 0xc420509ed8, ...)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/agent/hybrid/client.go:184 +0xdb
github.com/fnproject/fn/api/agent/hybrid.(*client).do(0xc4203f2c20, 0x55c2980, 0xc420192cf0, 0x0, 0x0, 0x4d7bbe0, 0xc4203f2e20, 0x4f7c908, 0x3, 0xc420509ed8, ...)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/agent/hybrid/client.go:161 +0x219
github.com/fnproject/fn/api/agent/hybrid.(*client).Dequeue(0xc4203f2c20, 0x55c2980, 0xc420192cf0, 0x0, 0x0, 0x0)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/agent/hybrid/client.go:83 +0x1a1
github.com/fnproject/fn/api/agent.(*CachedDataAccess).Dequeue(0xc420192960, 0x55c2940, 0xc42018c240, 0x55c2940, 0xc42018c240, 0xc4204f3280)
	<autogenerated>:1 +0x50
github.com/fnproject/fn/api/agent.(*agent).asyncChew.func1(0x55c28c0, 0xc4203c46c0, 0xc4203680c0, 0xc42018c1e0)
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/agent/async.go:53 +0xaa
created by github.com/fnproject/fn/api/agent.(*agent).asyncChew
	/Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn/api/agent/async.go:49 +0x7f
```

**Comment by rdallman** [comment]
this looks like a different error related to tracing ? can you rename issue correctly please and re-open? are you fixing or no?

**Comment by rdallman** [comment]
I can't repro based on the given parameter, fwiw, mine loops. i remember this being a tracing race, need to track it down in initialization
