### ISSUE TITLE
Internal Server Error setting up route

### ISSUE THREAD

**Issue by Empty2k12** [fnproject/fn#754]
I have been follwing the `Getting started` steps but I am running into the following problem:
```➜  hello fn --verbose deploy --app myapp --local
Deploying hello to app: myapp at path: /hello
Bumped to version 0.0.4
Building image empty2k12/hello:0.0.4
Sending build context to Docker daemon   5.12kB
Step 1/8 : FROM fnproject/go:dev as build-stage
 ---> 1b2c8e7b6de5
Step 2/8 : WORKDIR /function
 ---> Using cache
 ---> 3d553bba2e13
Step 3/8 : ADD . /go/src/func/
 ---> 342c98f4c1a3
Step 4/8 : RUN cd /go/src/func/ && go build -o func
 ---> Running in a1ff4831137c
Removing intermediate container a1ff4831137c
 ---> e05904aed150
Step 5/8 : FROM fnproject/go
 ---> ec8378042107
Step 6/8 : WORKDIR /function
 ---> Using cache
 ---> e4ea7a6477e3
Step 7/8 : COPY --from=build-stage /go/src/func/func /function/
 ---> Using cache
 ---> a37c5b4b262c
Step 8/8 : ENTRYPOINT ["./func"]
 ---> Using cache
 ---> a4804128f834
Successfully built a4804128f834
Successfully tagged empty2k12/hello:0.0.4

Updating route /hello using image empty2k12/hello:0.0.4...
ERROR: internal server error
```

**Comment by Empty2k12** [comment]
Here is the log outout as it appears in the `fn` Shell:

```
time="2018-02-11T20:16:13Z" level=error msg="internal server error" action="server.handleRoutesPostPutPatch)-fm" app=myapp error="unable to open database file" route=/hello stack="goroutine 5112 [running]:\nruntime/debug.Stack(0xc42006c370, 0x1898040, 0xc4205c0960)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x189f940, 0xc420646810, 0x7f365bb25890, 0xc42014a420, 0x1898040, 0xc4205c0960)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:42 +0x445\ngithub.com/fnproject/fn/api/server.handleErrorResponse(0xc42014a420, 0x1898040, 0xc4205c0960)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:24 +0xa9\ngithub.com/fnproject/fn/api/server.(*Server).handleRoutesPostPutPatch(0xc420241360, 0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/routes_create_update.go:38 +0x242\ngithub.com/fnproject/fn/api/server.(*Server).(github.com/fnproject/fn/api/server.handleRoutesPostPutPatch)-fm(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/server.go:453 +0x34\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.appNameCheck(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:105 +0xea\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).runMiddleware(0xc420241360, 0xc42014a420, 0x0, 0x0, 0x0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:57 +0x2e0\ngithub.com/fnproject/fn/api/server.(*Server).apiMiddlewareWrapper.func1(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:40 +0x58\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.setAppNameInCtx(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:95 +0x1b3\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).runMiddleware(0xc420241360, 0xc42014a420, 0x0, 0x0, 0x0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:57 +0x2e0\ngithub.com/fnproject/fn/api/server.(*Server).rootMiddlewareWrapper.func1(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:47 +0x4f\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:69 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.traceWrap(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:55 +0x397\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.loggerWrap(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:86 +0x192\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420265440, 0xc42014a420)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:332 +0x5b4\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420265440, 0x189e5c0, 0xc42064c0e0, 0xc420586300)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:296 +0x16b\nnet/http.serverHandler.ServeHTTP(0xc420318340, 0x189e5c0, 0xc42064c0e0, 0xc420586300)\n\t/usr/local/go/src/net/http/server.go:2619 +0xb4\nnet/http.(*conn).serve(0xc4202400a0, 0x189f880, 0xc4205bf0c0)\n\t/usr/local/go/src/net/http/server.go:1801 +0x71d\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2720 +0x288\n"
```

**Comment by Empty2k12** [comment]
A restart of `fn` fixed this problem, but error messages like `error="unable to open database file"` should be displayed to the user.
