### ISSUE TITLE
No logs generated for failed calls.

### ISSUE THREAD

**Issue by nicolasnoble** [fnproject/fn#995]
I was trying to (painfully) use serverless with fn from [the quickstart](https://serverless.com/framework/docs/providers/fn/guide/quick-start/), and while the deployment of the hello-world app is successful, I get an error 500 during the invocation. Trying to invoke from the web UI only yields the message "Something went terribly wrong (Status Code: 500)"

The problem with this is that while the failure counter is properly increased in the web UI, there is absolutely no log whatsoever:

```
$ fn calls l hello-world
$ fn logs g hello-world l
ERROR: No previous calls found.
```

I am at a loss trying to grasp how fn is emitting any log that would help me monitor and debug what's going on now.

**Comment by denismakogon** [comment]
Hi, Nicolas. Welcome. First of all, you need to ensure that you can call your function, try with `curl -v` because it's not really clear what's going on. Also, I'm not really sure that FN UI (if that is what you are referring to) is stable at this moment. So, would be nice if you can try to call your function with `fn -v call --include-call-id` or `curl -v`. Thanks.

**Comment by nicolasnoble** [comment]
Here's some more data, still without any callid generated, same error 500, and no logs:

```
$ fn apps l
hello-world
$ fn routes l hello-world
path    image                           endpoint
/hello  10.12.1.2:5000/hello:0.0.1      localhost:8080/r/hello-world/hello
$ curl -v localhost:8080/r/hello-world/hello
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /r/hello-world/hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=utf-8
< Fn_call_id: 01CDD773BMNG8G00GZJ000001K
< Date: Sun, 13 May 2018 17:01:52 GMT
< Content-Length: 46
<
{"error":{"message":"internal server error"}}
* Connection #0 to host localhost left intact
$ fn -v call --display-call-id hello-world hello
Call ID: 01CDD7EBDQNG8G00GZJ000001Q
{"error":{"message":"internal server error"}}
ERROR: error calling function: status 500
$ fn logs g hello-world l
ERROR: No previous calls found.
$ fn logs g hello-world 01CDD7EBDQNG8G00GZJ000001Q
ERROR: Call log not found
$ fn calls g hello-world 01CDD7EBDQNG8G00GZJ000001Q
ERROR: Call not found
```

Side notes: the `call` command isn't listed when doing `fn help`, while `fn help call` works fine. Also the proper argument is `--display-call-id`.

**Comment by denismakogon** [comment]
Can you check Fn logs? It seems like something is broken or not running well.

**Comment by nicolasnoble** [comment]
How do I do that? I couldn't find any documentation about where to find logs other than the `fn log` command that returns nothing.

**Comment by denismakogon** [comment]
Well, it depends on how you run Fn.

**Comment by nicolasnoble** [comment]
Right, of course. I dropped `fn start` into a screen and detached it to let it run. I didn't realize logs would then only be accessible from this console.

I am then getting this log line:
```
time="2018-05-13T17:25:27Z" level=info msg="Hot function launcher starting" action="server.handleFunctionCall)-fm" app=hello-world app_id=01CDD74TKPNG8G00GZJ000001J id=01CDD8J96XNG8G00GZJ0000001 launcher_timeout=1h0m0s route=/hello
time="2018-05-13T17:25:27Z" level=info msg="Hot function launcher starting hot container" action="server.handleFunctionCall)-fm" app=hello-world app_id=01CDD74TKPNG8G00GZJ000001J currentStats="{[0 1 0 0] [0 1 0 0 0 0]}" id=01CDD8J96XNG8G00GZJ0000001 isNeeded=true route=/hello
time="2018-05-13T17:25:27Z" level=error msg="internal server error" action="server.handleFunctionCall)-fm" app=hello-world error="parse 10.12.1.2:5000: first path segment in URL cannot contain colon" id=01CDD8J96XNG8G00GZJ0000001 route=/hello stack="goroutine 487 [running]:\nruntime/debug.Stack(0xc4209dfae0, 0x12272c0, 0xc42082f1a0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x1231d00, 0xc42082f020, 0x7f567a2ee000, 0xc42068e9a0, 0x12272c0, 0xc42082f1a0)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:42 +0x429\ngithub.com/fnproject/fn/api/server.handleErrorResponse(0xc42068e9a0, 0x12272c0, 0xc42082f1a0)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:24 +0xa9\ngithub.com/fnproject/fn/api/server.(*Server).handleFunctionCall(0xc420472000, 0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/runner.go:24 +0x66\ngithub.com/fnproject/fn/api/server.(*Server).(github.com/fnproject/fn/api/server.handleFunctionCall)-fm(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/server.go:879 +0x34\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).checkAppPresenceByNameAtRunner.func1(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:113 +0x12d\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).runMiddleware(0xc420472000, 0xc42068e9a0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:73 +0x29f\ngithub.com/fnproject/fn/api/server.(*Server).rootMiddlewareWrapper.func1(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:63 +0x58\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:77 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.traceWrap(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:63 +0x3da\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/api/server.loggerWrap(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:94 +0x18e\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4203be120, 0xc42068e9a0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:332 +0x585\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4203be120, 0x12305c0, 0xc420203a40, 0xc4205dda00)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:296 +0x153\ngithub.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc4200df540, 0x12305c0, 0xc420203a40, 0xc4205dda00)\n\t/go/src/github.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp/server.go:75 +0x109\nnet/http.serverHandler.ServeHTTP(0xc4206912b0, 0x1230d80, 0xc42017eb60, 0xc4205dd900)\n\t/usr/local/go/src/net/http/server.go:2694 +0xbc\nnet/http.(*conn).serve(0xc4201fc500, 0x1231c40, 0xc4206743c0)\n\t/usr/local/go/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2795 +0x27b\n"
```

Interestingly, 10.12.1.2:5000 is my local docker registry. In fact, it's right in the "image" column of doing `fn routes l hello-world`. So I guess Fn currently doesn't properly support local registry down to its core, unlike what the [documentation seems to indicate](https://github.com/fnproject/fn#quickstart) ? Note that the image name is proper and is accepted by docker:

```
$ docker run 10.12.1.2:5000/hello:0.0.1
I show up in the logs name was: World
[object Object]
```

**Comment by denismakogon** [comment]
> Right, of course. I dropped fn start into a screen and detached it to let it run. I didn't realize logs would then only be accessible from this console.

this is a type of error that happens before an actual function call, so, it gets resolved to http 500, but i do agree that it's not user-friendly.

> Interestingly, 10.12.1.2:5000 is my local docker registry. In fact, it's right in the "image" column of doing fn routes l hello-world

Unfortunately, it seems it doesn't work properly, was able to reproduce your error. As a way to fix your problem fast, make your docker talk to your registry and Fn will talk to your docker, so Fn wouldn't need to talk to your registry. I'll open an issue for this case.

**Comment by denismakogon** [comment]
you nee to add schema in front, `10.12.1.2:5000/image:0.0.1` wouldn't work, but `http://10.12.1.2:5000/image:0.0.1` would.

**Comment by denismakogon** [comment]
@rdallman @skinowski https://play.golang.org/p/x3IWnIYTW9f

**Comment by nicolasnoble** [comment]
Unfortunately, you can't unilaterally add this to `FN_REGISTRY`. The scripts in your https://github.com/fnproject/serverless-fn project will then try to run the command `docker build -t http://10.12.1.2:5000/hello:0.0.1`, which is then in turn invalid. And you can't presume which of http:// or https:// to add in front automatically, since this is up to docker itself to determine which scheme to use based on its configuration settings.

So there's a tug-of-war here between Fn and docker. One seems to want the schema in front of the image name to access the registry, and the other one doesn't.

**Comment by denismakogon** [comment]
cc @hibooboo2

**Comment by hibooboo2** [comment]
Yeah @nicolasnoble Is correct. Having the scheme in the image name is incorrect. And I am not sure why we are automatically adding https we should not be as we do not know which it should be. Not sure why I was pinged. Are you saying I should strip the prefix for https:// or http:// if it exists when I perform the docker build in the serverless plugin for serverless?

**Comment by denismakogon** [comment]
just wanted to clarify whether agent's driver must be a little bit more safe for such cases or we should enforce people who use custom registries to specify URL schema. I think we need to enforce everyone to put schema in from because we delegate too many decisions to Fn. To be honest, i have no idea why docker CLI does not require a schema, but that's what it has, we don't have to follow the same way.

**Comment by hibooboo2** [comment]
I would say its a decision that the team should make. But I agree that ambiguity is not great.

**Comment by nicolasnoble** [comment]
@denismakogon the fact that docker really doesn't want a schema means that you can't propagate the same image name down. I'd say you have to follow the same way for consistency, otherwise you're going to be unable to create and push images remotely in a sane and consistent manner.

Also you can't randomly add http or https in front of it, unless you can parse docker's configuration, which should ideally be out of reach from your process.

For instance, in my `/etc/docker/daemon.json` file, I have the following section:
```
  "insecure-registries":
    [
      "10.12.1.2:5000"
    ],
```

which then tells the daemon that the http scheme needs to be used to access this registry. This directory by default is 700 owned by root:root, and this is okay because only the daemon needs to be able to read and access it. So unless you want to make your process able to read docker's settings (using whichever way the admin of the system wanted them to be stored), or to have duplication of the configuration data in it, you can't pick between http or https.

**Comment by denismakogon** [comment]
That's weird, because native docker SDK forces its users to specify schema: https://github.com/docker/distribution/blob/0700fa570d7bcc1b3e46ee127c4489fd25f4daa3/registry/api/v2/urls.go#L38
and here's the code fn relies on: https://github.com/docker/distribution/blob/8cedd7b3a49e719220c77584e42b7c7386fba811/registry/client/repository.go#L135

so, docke CLI seems like steped away from core principles, i.e. docker CLI and SDK is not consistent to each other.
So, according to SDK and registry API, URL schema is required, meaning Fn must require URL schema as part of registry.

**Comment by rdallman** [comment]
when we're talking to registry API we need scheme (so configured registry with scheme), but the image itself needs to not have scheme (as outlined by docker's image spec, and as stated). this is kinda confusing, agreed. the registry must be configured against FN for this to work at all, due to us using the registry API (we use this to check the size of images before downloading them, it's an optional feature, but also to check existence)

this issue of using the local registry has come up numerous times now, we need to make it less easy for it to blow up as either it blows up for most users that try it or the users that it doesn't blow up for we don't hear from and it's not as bad as we might think, but it's at least 3-4 now. CLI doesn't even work properly with private registry in some obvious cases https://github.com/fnproject/cli/pull/144

one option to load in the whole docker config is to build the fn image with an additional docker configuration. e.g.:

```
FROM fnproject/fnserver

ADD /etc/docker/daemon.json mydockerconfig.json
```

this is a painful additional step and should be avoidable in more trivial (most) installs.

fwiw, it is possible to run a function from a private registry with FN as it is today. the configuration, however, seems to be very error prone (we should fix this).
